### ISSUE TITLE
Wrapping up camera app

### ISSUE THREAD

**Issue by natezzz** [Sushisushi-sandesu/sushi#22]
Implement camera app UI.

**Comment by takuti** [comment]
I have tried [Leap Motion + Unity widgets](https://developer.leapmotion.com/documentation/unity/unity/Unity_Widgets.html), and it works as we desired: Sushisushi-sandesu/sushi/pull/23.

If the widget also works on the Oculus screen, I guess you can directly use these widgets' UI as a part of the camera app. (i.e. taking photo by pressing the widget button instead of pressing F key)

**Comment by natezzz** [comment]
@takuti Thank you for finding this good library! It looks very nice.
Ok I'll try if it works on the camera app.

**Comment by takuti** [comment]
Hi @natezzz and @neetp7k9,

Now, your task is to implement:
- [x] Press O key :arrow_right: (event) :arrow_right: open canvas
- [x] Press F key :arrow_right: (event) :arrow_right: take a screenshot
- [x] Press C key :arrow_right: (event) :arrow_right: close window

w/ improving app UI.

We can easily integrate your camera app with Leap motion by just replacing the hooked event. (key pressing -> gesture)
